version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - run: npm install
      - save_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ arch }}
          paths:
            - node_modules
      - run: npm run test
  deploy:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "package-lock.json" }}-{{ arch }}
      - run: npm run deploy
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

