version: 2
jobs:
  build:
    docker:
      - image: 'circleci/node:latest'
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "Build success"
      - run: echo "Build piu" >> build.txt
  deploy:
    working_directory: ~/repo
    steps:
      - run: echo "Deploy"
      - run: cat build.txt
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build

